---
title: "Optimal ID equity analysis report"

header-includes:
    - \usepackage{caption}

params:
  data: NA
  file: NA
  run_notes: NA
  filter_group: NA
  data_filter_string: NA
  group_filter_string: NA
  filter_ref_grp1: NA
  filter_ref_grp2: NA
  filter_ref_grp3: NA
  group: NA
  reference_grp1: NA
  reference_grp2: NA
  
  last_pathway: NA
  listwise: NA
  
  pathway_name: NA
  pathway_name2: NA
  pathway_name3: NA
  pathway_name4: NA
  
  assessments: NA
  assessments2: NA
  assessments3: NA
  assessments4: NA
  
  weights: NA
  weights2: NA
  weights3: NA
  weights4: NA
  
  nom: NA
  nom2: NA
  nom3: NA
  nom4: NA
  
  nom_cutoff: NA
  nom_cutoff2: NA
  nom_cutoff3: NA
  nom_cutoff4: NA
  
  mean_cutoff: NA
  mean_cutoff2: NA
  mean_cutoff3: NA
  mean_cutoff4: NA
  
  baseline_id_var: NA
  group_stats_tbl: NA

---


\captionsetup[table]{labelformat=empty}


```{r load-packages, include=FALSE}
library(dplyr)
library(ggplot2)
library(data.table)
library(kableExtra)
library(flextable)
library(knitr)
library(rmarkdown)
library(officer)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,
                      echo = FALSE, 
                      fig.width=11, 
                      fig.height=8, 
                      dpi=150, 
                      ft.align = "left",
                      tab.cap.pre=' ', 
                      tab.cap.sep='',
                      tab.cap='',
                      tab.cap.tnd="")

set_flextable_defaults(fonts_ignore=TRUE)
```

This report was created using the [Optimal ID equity explorer app](https://mmcbee.shinyapps.io/OptimalID_Equity_shiny/). It was generated on `r format(Sys.time(), '%d %B %Y')` at `r format(Sys.time(), '%H:%M')`.




`r ifelse(params$run_notes != '', paste("**Notes**:", params$run_notes), '')`


```{r filter-and-group-strings}
# construct filtering and group selection strings
if (!is.null(params$filter_group)) {

      data_filter_string = paste0(params$filter_group[1], " == (",
                                  toString(params$filter_ref_grp1), ")")


      if (length(params$filter_group) >= 2) {

        data_filter_string = paste0(data_filter_string, " & ",
                                      params$filter_group[2], " == (",
                                      toString(params$filter_ref_grp2), ")")
        }

      if (length(params$filter_group) >= 3) {

        data_filter_string = paste0(data_filter_string, " & ",
                                      params$filter_group[3], " == (",
                                      toString(params$filter_ref_grp3), ")")
        }

    } else if (is.null(params$filter_group)) {
      data_filter_string = 'No data filtering applied (all rows selected)'
    }


if (!is.null(params$group)) {

      filter_string = paste0(params$group[1], " == (",
                                  toString(params$reference_grp1), ")")


      if (length(params$group) >= 2) {

        filter_string = paste0(filter_string, " & ",
                                      params$group[2], " == (",
                                      toString(params$reference_grp2), ")")
        }

    } else if (is.null(params$group)) {
      filter_string = 'No equity groups selected'
    }


```


```{r construct-pathways}
# construct the pathways from the input, used to construct the equity statistics table
#  and the plots

pathways = list()

pathways = append(pathways, list(pathway_1 = list(
    assessments=params$assessments,
    listwise=params$listwise,
    nom=params$nom,
    nom_cutoff=params$nom_cutoff,
    test_cutoff=params$mean_cutoff,
    weights=params$weights)
    )
)


if (params$last_pathway >= 2 & !is.null(params$assessments2) &
    !is.null(params$nom2)) {

    pathways = append(pathways, list(pathway_2 = list(
        assessments=params$assessments2,
        listwise=params$listwise,
        nom=params$nom2,
        nom_cutoff=params$nom_cutoff2,
        test_cutoff=params$mean_cutoff2,
        weights=params$weights2)
    )
    )
}

if (params$last_pathway >= 3 & !is.null(params$assessments3) &
    !is.null(params$nom3)) {

    pathways = append(pathways, list(pathway_3 = list(
        assessments=params$assessments3,
        listwise=params$listwise,
        nom=params$nom3,
        nom_cutoff=params$nom_cutoff3,
        test_cutoff=params$mean_cutoff3,
        weights=params$weights3)
    )
    )
}

if (params$last_pathway >= 4 & !is.null(params$assessments4) &
    !is.null(params$nom)) {

    pathways = append(pathways, list(pathway_4 = list(
        assessments=params$assessments4,
        listwise=params$listwise,
        nom=params$nom4,
        nom_cutoff=params$nom_cutoff4,
        test_cutoff=params$mean_cutoff4,
        weights=params$weights4)
    )
    )
}
```



```{r build-settings-table}
settings_tbl = data.frame(
  Parameter = c('Uploaded file', 
                'Data filtering', 
                'Group(s) selected for equity analysis',
                'Reference equity group',
                'Baseline identification indicator variable name'),
  Setting = c(params$file, 
              toString(data_filter_string),
              toString(params$group),
              toString(filter_string),
              params$baseline_id_var
  ))
              
              
              

settings_tbl %>% flextable() %>% autofit() %>% theme_zebra() %>% set_caption(
  caption = 'Table 1: Settings',
  autonum = run_autonum(),
  style = "paragraph",
  html_escape = TRUE
) %>% fit_to_width(7)

```

<br>

```{r pathway1-table}
if (params$last_pathway >= 1) {
  
  pathway1_tbl = data.frame(
    Parameter = c('Pathway name',
                  'Nomination (phase-1) assessment', 
                  'Nomination (phase-1) percentile cutoff', 
                  'Phase-2 assessments',
                  'Phase-2 assessment weights',
                  'Phase-2 percentile cutoff'),
    Setting = c(toString(params$pathway_name), 
                toString(params$nom),
                toString(params$nom_cutoff),
                toString(params$assessments),
                toString(params$weights),
                toString(params$mean_cutoff)
    ))
  
  pathway1_tbl %>% flextable() %>% autofit() %>% theme_zebra() %>% set_caption(
    caption = 'Table 2A: Pathway 1',
    autonum = run_autonum(),
    style = "paragraph",
    html_escape = TRUE
  ) %>% fit_to_width(7)
  
}
```

<br>


```{r, pathway2-table}
if (params$last_pathway >= 2) {
  
  pathway2_tbl = data.frame(
    Parameter = c('Pathway name',
                  'Nomination (phase-1) assessment', 
                  'Nomination (phase-1) percentile cutoff', 
                  'Phase-2 assessments',
                  'Phase-2 assessment weights',
                  'Phase-2 percentile cutoff'),
    Setting = c(toString(params$pathway_name2), 
                toString(params$nom2),
                toString(params$nom_cutoff2),
                toString(params$assessments2),
                toString(params$weights2),
                toString(params$mean_cutoff2)
    ))
  
  pathway2_tbl %>% flextable() %>% autofit() %>% theme_zebra() %>% set_caption(
    caption = 'Table 2B: Pathway 2',
    autonum = run_autonum(),
    style = "paragraph",
    html_escape = TRUE
  ) %>% fit_to_width(7)
  
}
```

<br>

```{r pathway3-table}

if (params$last_pathway >= 3) {
  
  pathway1_tbl = data.frame(
    Parameter = c('Pathway name',
                  'Nomination (phase-1) assessment', 
                  'Nomination (phase-1) percentile cutoff', 
                  'Phase-2 assessments',
                  'Phase-2 assessment weights',
                  'Phase-2 percentile cutoff'),
    Setting = c(toString(params$pathway_name3), 
                toString(params$nom3),
                toString(params$nom_cutoff3),
                toString(params$assessments3),
                toString(params$weights3),
                toString(params$mean_cutoff3)
    ))
  
  pathway3_tbl %>% flextable() %>% autofit() %>% theme_zebra() %>% set_caption(
    caption = 'Table 2C: Pathway 3',
    autonum = run_autonum(),
    style = "paragraph",
    html_escape = TRUE
  ) %>% fit_to_width(7)
  
}
```

<br>


```{r pathway4-table}

if (params$last_pathway >= 4) {
  
  pathway4_tbl = data.frame(
    Parameter = c('Pathway name',
                  'Nomination (phase-1) assessment', 
                  'Nomination (phase-1) percentile cutoff', 
                  'Phase-2 assessments',
                  'Phase-2 assessment weights',
                  'Phase-2 percentile cutoff'),
    Setting = c(toString(params$pathway_name4), 
                toString(params$nom4),
                toString(params$nom_cutoff4),
                toString(params$assessments4),
                toString(params$weights4),
                toString(params$mean_cutoff4)
    ))
  
  pathway4_tbl %>% flextable() %>% autofit() %>% theme_zebra() %>% set_caption(
    caption = 'Table 2D: Pathway 4',
    autonum = run_autonum(),
    style = "paragraph",
    html_escape = TRUE
  ) %>% fit_to_width(7)
  
}
```

<br>

```{r build-equity-table, warnings=FALSE}


if (!is.null(params$group) & 
        (!is.null(params$assessments) | 
         !is.null(params$assessments2) |
         !is.null(params$assessments3) |
         !is.null(params$assessments4) ) &
        (!is.null(params$nom) |
         !is.null(params$nom2) |
         !is.null(params$nom3) |
         !is.null(params$nom4)) ) {
  
  results = list()
      
  pathway_label_list = list(
      params$pathway_name,
      params$pathway_name2,
      params$pathway_name3,
      params$pathway_name4
  )
  
  pathway_label_list[[length(pathways)+1]] = "Identified under any pathway"
  
  
  for (i in 1:(length(pathways)+1)) {
    
    this_result = equity_plot_multi(data=params$data, 
                                group=params$group,
                                reference_grp=params$group_filter_string,
                                pathways=pathways,
                                baseline_id_var=params$baseline_id_var,
                                plot_metric='Count',
                                selected_pathway=i,
                                selected_pathway_name=pathway_label_list[[i]])$summary_tbl
    
    if (i < (length(pathways)+1)) {
      results[[i]] = process_equity_tbl(tbl=this_result,
                                        group=params$group,
                                        pathway_lbl=pathway_label_list[[i]], 
                                        pathway_num=i
                                        ) 
    } else {
     
      if (length(pathways) > 1) {
        results[[i]] = process_equity_tbl(tbl=this_result,
                                          group=params$group,
                                          pathway_lbl="Any pathway", 
                                          pathway_num=i) 
      }
    }
  }

  equity_table = do.call('rbind', results)

  equity_table %>% distinct() %>% arrange(comparison) %>% flextable() %>% autofit() %>% 
    theme_zebra() %>% set_caption(
    caption = 'Table 3: Population size and equity metrics',
    autonum = NULL,
    style = "Table Caption",
    html_escape = TRUE
  ) %>% fit_to_width(7)
    
}

```

<br>

```{r build-descriptives-table}

if (!is.null(params$group_stats_tbl)) {
  
  params$group_stats_tbl %>% distinct() %>% regulartable() %>% autofit() %>% theme_zebra() %>% set_caption(
    caption = 'Table 4: Assessment descriptive statistics by group',
    autonum = NULL,
    style = "Table Caption",
    html_escape = TRUE
  ) %>% fit_to_width(7)
  
}
```

<!-- -->


```{r build-plots}

metrics = c("Count", "Representation Index", "Proportion Identified",
                        "Relative Risk")


paths = if(params$last_pathway == 1) {               
               1} else {
                 1:(params$last_pathway + 1)
                 }

plot_params = expand_grid(metrics, paths)


plots = mapply(equity_plot_multi, 
               plot_metric = plot_params[["metrics"]],
               selected_pathway = plot_params[["paths"]],
               selected_pathway_name = pathway_label_list[plot_params[["paths"]]],
               MoreArgs=list(
                  data=params$data,
                  group=params$group,
                  reference_grp=params$group_filter_string,
                  pathways=pathways,
                  baseline_id_var=params$baseline_id_var),
               SIMPLIFY = FALSE)

```

```{r plot11}
if (length(plots) >= 1) {
  plots[[1]]$p
}

```

<br>

```{r plot12}
if (length(plots) >= 2) {
  plots[[2]]$p
}
```

<br>

```{r plot13}
if (length(plots) >= 3) {
  plots[[3]]$p
}
```

<br>

```{r plot14}
if (length(plots) >= 4) {
  plots[[4]]$p
}
```

<br>

```{r, plot21}
if (length(plots) >= 5) {
  plots[[5]]$p
}
```

<br>

```{r plot22}
if (length(plots) >= 6) {
  plots[[6]]$p
}
```

<br>

```{r plot23}
if (length(plots) >= 7) {
  plots[[7]]$p
}
```

<br>

```{r plot24}
if (length(plots) >= 8) {
  plots[[8]]$p
}
```

<br>

```{r plot31}
if (length(plots) >= 9) {
  plots[[9]]$p
}
```

<br>

```{r plot32}
if (length(plots) >= 10) {
  plots[[10]]$p
}
```

<br>

```{r plot33}
if (length(plots) >= 11) {
  plots[[11]]$p
}
```

<br>

```{r plot34}
if (length(plots) >= 12) {
  plots[[12]]$p
}
```

<br>

```{r plot41}
if (length(plots) >= 13) {
  plots[[13]]$p
}
```

<br>

```{r plot42}
if (length(plots) >= 14) {
  plots[[14]]$p
}
```

<br>

```{r plot43}
if (length(plots) >= 15) {
  plots[[15]]$p
}
```

<br>

```{r plot44}
if (length(plots) >= 16) {
  plots[[16]]$p
}
```

<br>

```{r plot51}
if (length(plots) >= 17) {
  plots[[17]]$p
}
```

<br>

```{r plot52}
if (length(plots) >= 18) {
  plots[[18]]$p
}
```

<br>

```{r plot53}
if (length(plots) >= 19) {
  plots[[19]]$p
}
```

<br>

```{r plot54}
if (length(plots) >= 20) {
  plots[[20]]$p
}
```

